### ISSUE TITLE
image: support for stable/development tags

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-auth-vomsproxy#7]
(1) Having a quick look on the GitHub actions, are we pushing `latest` tag for the master branch HEAD? We should rather avoid this, the `latest` tag is only used for local developments, otherwise in the cluster we usually have image pulling policy `IfNotPresent`, so `latest` should be avoided there.  (Ditto for krb5 which will come later once we clean this.)  See e.g. [What's wrong with the latest tag](https://vsupalov.com/docker-latest-tag/) blog post.

(2) For stable releases, once we have a first version working, we should tag it and amend GitHub actions to be pushing nicely tagged releases such as `1.0.0`. 

(3) For development releases, we can use `git describe --dirty` technique to generate nice image tag, see also work on creating stable/development images for the main Helm charts.

**Comment by clelange** [comment]
ad (1): We push both `latest` and the short SHA. I think this is fine.

ad (2) I agree, we can simply do this on `tag`

(3) Not needed in my opinion due to (1)

**Comment by tiborsimko** [comment]
The tag `1.0.0` was released some weeks ago, and it is pinned in the REANA cluster.  Closing the issue.
